/********************************************************************************
** Form generated from reading UI file 'BV.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_BV_H
#define UI_BV_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_BVClass
{
public:
    QAction *action;
    QAction *action2;
    QWidget *centralWidget;
    QLabel *label_2;
    QPushButton *pushButtonTemperature;
    QPushButton *pushButton;
    QPushButton *pushButtonSlot1;
    QPushButton *pushButtonSlot2;
    QPushButton *pushButtonSlot3;
    QPushButton *pushButtonSlot4;
    QPushButton *pushButtonSlot5;
    QPushButton *pushButtonSlot6;
    QPushButton *pushButtonSlot7;
    QPushButton *pushButtonSlot8;
    QPushButton *pushButtonSlot9;
    QPushButton *pushButtonSlot10;
    QPushButton *pushButtonSlot11;
    QPushButton *pushButtonSlot12;
    QPushButton *pushButtonSlot13;
    QPushButton *pushButtonSlot14;
    QPushButton *pushButtonSlot15;
    QLabel *label_4;
    QLabel *labelSlot1_1;
    QLabel *labelSlot1_2;
    QLabel *labelSlot1_3;
    QLabel *labelSlot1_4;
    QLabel *labelSlot1_5;
    QLabel *labelSlot1_6;
    QLabel *labelSlot1_7;
    QLabel *labelSlot1_8;
    QLabel *labelSlot1_9;
    QLabel *labelSlot1_10;
    QLabel *labelSlot1_11;
    QLabel *labelSlot1_12;
    QLabel *labelSlot1_13;
    QLabel *labelSlot1_14;
    QLabel *labelSlot1_15;
    QLabel *label_5;
    QLineEdit *lineEditName1_1;
    QLabel *label_6;
    QLabel *label_7;
    QComboBox *comboBoxSex1;
    QLabel *label_8;
    QLineEdit *lineEditPH_1;
    QLabel *label_9;
    QLabel *label_1time;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *labeltempCondition;
    QPushButton *saveButton1;
    QPushButton *saveButton2;
    QPushButton *saveButton3;
    QPushButton *saveButton4;
    QPushButton *saveButton5;
    QPushButton *saveButton6;
    QPushButton *saveButton7;
    QPushButton *saveButton8;
    QPushButton *saveButton9;
    QPushButton *saveButton10;
    QPushButton *saveButton11;
    QPushButton *saveButton12;
    QPushButton *saveButton13;
    QPushButton *saveButton14;
    QPushButton *saveButton15;
    QLineEdit *lineEditName1_2;
    QLineEdit *lineEditName1_3;
    QLineEdit *lineEditName1_4;
    QLineEdit *lineEditName1_5;
    QLineEdit *lineEditName1_6;
    QLineEdit *lineEditName1_7;
    QLineEdit *lineEditName1_8;
    QLineEdit *lineEditName1_9;
    QLineEdit *lineEditName1_10;
    QLineEdit *lineEditName1_11;
    QLineEdit *lineEditName1_12;
    QLineEdit *lineEditName1_13;
    QLineEdit *lineEditName1_14;
    QLineEdit *lineEditName1_15;
    QComboBox *comboBoxSex1_2;
    QComboBox *comboBoxSex1_3;
    QComboBox *comboBoxSex1_4;
    QComboBox *comboBoxSex1_5;
    QComboBox *comboBoxSex1_6;
    QComboBox *comboBoxSex1_7;
    QComboBox *comboBoxSex1_8;
    QComboBox *comboBoxSex1_9;
    QComboBox *comboBoxSex1_10;
    QComboBox *comboBoxSex1_11;
    QComboBox *comboBoxSex1_12;
    QComboBox *comboBoxSex1_13;
    QComboBox *comboBoxSex1_14;
    QComboBox *comboBoxSex1_15;
    QLineEdit *lineEditPH_2;
    QLineEdit *lineEditPH_3;
    QLineEdit *lineEditPH_4;
    QLineEdit *lineEditPH_5;
    QLineEdit *lineEditPH_6;
    QLineEdit *lineEditPH_7;
    QLineEdit *lineEditPH_8;
    QLineEdit *lineEditPH_9;
    QLineEdit *lineEditPH_10;
    QLineEdit *lineEditPH_11;
    QLineEdit *lineEditPH_12;
    QLineEdit *lineEditPH_13;
    QLineEdit *lineEditPH_14;
    QLineEdit *lineEditPH_15;
    QLabel *label_1time_2;
    QLabel *label_1time_3;
    QLabel *label_1time_4;
    QLabel *label_1time_5;
    QLabel *label_1time_6;
    QLabel *label_1time_7;
    QLabel *label_1time_8;
    QLabel *label_1time_9;
    QLabel *label_1time_10;
    QLabel *label_1time_11;
    QLabel *label_1time_12;
    QLabel *label_1time_13;
    QLabel *label_1time_14;
    QLabel *label_1time_15;
    QLabel *label_10;
    QPushButton *pushButton_2;
    QLabel *label;
    QLineEdit *lineEditNAG_1;
    QLineEdit *lineEditNAG_2;
    QLineEdit *lineEditNAG_3;
    QLineEdit *lineEditNAG_4;
    QLineEdit *lineEditNAG_5;
    QLineEdit *lineEditNAG_6;
    QLineEdit *lineEditNAG_7;
    QLineEdit *lineEditNAG_8;
    QLineEdit *lineEditNAG_9;
    QLineEdit *lineEditNAG_10;
    QLineEdit *lineEditNAG_11;
    QLineEdit *lineEditNAG_12;
    QLineEdit *lineEditNAG_13;
    QLineEdit *lineEditNAG_14;
    QLineEdit *lineEditNAG_15;
    QLabel *label_13;
    QLineEdit *lineEditPLD_1;
    QLineEdit *lineEditPLD_2;
    QLineEdit *lineEditPLD_3;
    QLineEdit *lineEditPLD_4;
    QLineEdit *lineEditPLD_5;
    QLineEdit *lineEditPLD_6;
    QLineEdit *lineEditPLD_7;
    QLineEdit *lineEditPLD_8;
    QLineEdit *lineEditPLD_9;
    QLineEdit *lineEditPLD_10;
    QLineEdit *lineEditPLD_11;
    QLineEdit *lineEditPLD_12;
    QLineEdit *lineEditPLD_13;
    QLineEdit *lineEditPLD_14;
    QLineEdit *lineEditPLD_15;
    QLabel *label_14;
    QLineEdit *lineEditSIA_1;
    QLineEdit *lineEditSIA_2;
    QLineEdit *lineEditSIA_3;
    QLineEdit *lineEditSIA_4;
    QLineEdit *lineEditSIA_5;
    QLineEdit *lineEditSIA_6;
    QLineEdit *lineEditSIA_7;
    QLineEdit *lineEditSIA_8;
    QLineEdit *lineEditSIA_9;
    QLineEdit *lineEditSIA_10;
    QLineEdit *lineEditSIA_11;
    QLineEdit *lineEditSIA_12;
    QLineEdit *lineEditSIA_13;
    QLineEdit *lineEditSIA_14;
    QLineEdit *lineEditSIA_15;
    QLabel *label_15;
    QLineEdit *lineEditLE_1;
    QLineEdit *lineEditLE_2;
    QLineEdit *lineEditLE_3;
    QLineEdit *lineEditLE_4;
    QLineEdit *lineEditLE_5;
    QLineEdit *lineEditLE_6;
    QLineEdit *lineEditLE_7;
    QLineEdit *lineEditLE_8;
    QLineEdit *lineEditLE_9;
    QLineEdit *lineEditLE_10;
    QLineEdit *lineEditLE_11;
    QLineEdit *lineEditLE_12;
    QLineEdit *lineEditLE_13;
    QLineEdit *lineEditLE_14;
    QLineEdit *lineEditLE_15;
    QLabel *label_16;
    QLineEdit *lineEditHH_1;
    QLineEdit *lineEditHH_2;
    QLineEdit *lineEditHH_3;
    QLineEdit *lineEditHH_4;
    QLineEdit *lineEditHH_5;
    QLineEdit *lineEditHH_6;
    QLineEdit *lineEditHH_7;
    QLineEdit *lineEditHH_8;
    QLineEdit *lineEditHH_9;
    QLineEdit *lineEditHH_10;
    QLineEdit *lineEditHH_11;
    QLineEdit *lineEditHH_12;
    QLineEdit *lineEditHH_13;
    QLineEdit *lineEditHH_14;
    QLineEdit *lineEditHH_15;
    QLabel *label_17;
    QLabel *filepath;
    QLineEdit *lineEditNumber_1;
    QLineEdit *lineEditNumber_2;
    QLineEdit *lineEditNumber_3;
    QLineEdit *lineEditNumber_4;
    QLineEdit *lineEditNumber_5;
    QLineEdit *lineEditNumber_6;
    QLineEdit *lineEditNumber_7;
    QLineEdit *lineEditNumber_8;
    QLineEdit *lineEditNumber_9;
    QLineEdit *lineEditNumber_10;
    QLineEdit *lineEditNumber_11;
    QLineEdit *lineEditNumber_12;
    QLineEdit *lineEditNumber_13;
    QLineEdit *lineEditNumber_14;
    QLineEdit *lineEditNumber_15;
    QLCDNumber *lcdNumber;
    QLCDNumber *lcdNumber_temperature;
    QMenuBar *menuBar;
    QMenu *menu;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *BVClass)
    {
        if (BVClass->objectName().isEmpty())
            BVClass->setObjectName(QStringLiteral("BVClass"));
        BVClass->resize(1178, 670);
        QIcon icon;
        icon.addFile(QStringLiteral("../../../a.ico"), QSize(), QIcon::Normal, QIcon::Off);
        BVClass->setWindowIcon(icon);
        action = new QAction(BVClass);
        action->setObjectName(QStringLiteral("action"));
        action2 = new QAction(BVClass);
        action2->setObjectName(QStringLiteral("action2"));
        centralWidget = new QWidget(BVClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(0, 90, 111, 16));
        pushButtonTemperature = new QPushButton(centralWidget);
        pushButtonTemperature->setObjectName(QStringLiteral("pushButtonTemperature"));
        pushButtonTemperature->setGeometry(QRect(0, 0, 75, 31));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(1090, 0, 75, 23));
        pushButtonSlot1 = new QPushButton(centralWidget);
        pushButtonSlot1->setObjectName(QStringLiteral("pushButtonSlot1"));
        pushButtonSlot1->setGeometry(QRect(10, 160, 75, 23));
        pushButtonSlot2 = new QPushButton(centralWidget);
        pushButtonSlot2->setObjectName(QStringLiteral("pushButtonSlot2"));
        pushButtonSlot2->setGeometry(QRect(10, 190, 75, 23));
        pushButtonSlot3 = new QPushButton(centralWidget);
        pushButtonSlot3->setObjectName(QStringLiteral("pushButtonSlot3"));
        pushButtonSlot3->setGeometry(QRect(10, 220, 75, 23));
        pushButtonSlot4 = new QPushButton(centralWidget);
        pushButtonSlot4->setObjectName(QStringLiteral("pushButtonSlot4"));
        pushButtonSlot4->setGeometry(QRect(10, 250, 75, 23));
        pushButtonSlot5 = new QPushButton(centralWidget);
        pushButtonSlot5->setObjectName(QStringLiteral("pushButtonSlot5"));
        pushButtonSlot5->setGeometry(QRect(10, 280, 75, 23));
        pushButtonSlot6 = new QPushButton(centralWidget);
        pushButtonSlot6->setObjectName(QStringLiteral("pushButtonSlot6"));
        pushButtonSlot6->setGeometry(QRect(10, 310, 75, 23));
        pushButtonSlot7 = new QPushButton(centralWidget);
        pushButtonSlot7->setObjectName(QStringLiteral("pushButtonSlot7"));
        pushButtonSlot7->setGeometry(QRect(10, 340, 75, 23));
        pushButtonSlot8 = new QPushButton(centralWidget);
        pushButtonSlot8->setObjectName(QStringLiteral("pushButtonSlot8"));
        pushButtonSlot8->setGeometry(QRect(10, 370, 75, 23));
        pushButtonSlot9 = new QPushButton(centralWidget);
        pushButtonSlot9->setObjectName(QStringLiteral("pushButtonSlot9"));
        pushButtonSlot9->setGeometry(QRect(10, 400, 75, 23));
        pushButtonSlot10 = new QPushButton(centralWidget);
        pushButtonSlot10->setObjectName(QStringLiteral("pushButtonSlot10"));
        pushButtonSlot10->setGeometry(QRect(10, 430, 75, 23));
        pushButtonSlot11 = new QPushButton(centralWidget);
        pushButtonSlot11->setObjectName(QStringLiteral("pushButtonSlot11"));
        pushButtonSlot11->setGeometry(QRect(10, 460, 75, 23));
        pushButtonSlot12 = new QPushButton(centralWidget);
        pushButtonSlot12->setObjectName(QStringLiteral("pushButtonSlot12"));
        pushButtonSlot12->setGeometry(QRect(10, 490, 75, 23));
        pushButtonSlot13 = new QPushButton(centralWidget);
        pushButtonSlot13->setObjectName(QStringLiteral("pushButtonSlot13"));
        pushButtonSlot13->setGeometry(QRect(10, 520, 75, 23));
        pushButtonSlot14 = new QPushButton(centralWidget);
        pushButtonSlot14->setObjectName(QStringLiteral("pushButtonSlot14"));
        pushButtonSlot14->setGeometry(QRect(10, 550, 75, 23));
        pushButtonSlot15 = new QPushButton(centralWidget);
        pushButtonSlot15->setObjectName(QStringLiteral("pushButtonSlot15"));
        pushButtonSlot15->setGeometry(QRect(10, 580, 75, 23));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(100, 120, 81, 21));
        labelSlot1_1 = new QLabel(centralWidget);
        labelSlot1_1->setObjectName(QStringLiteral("labelSlot1_1"));
        labelSlot1_1->setGeometry(QRect(100, 160, 81, 21));
        labelSlot1_2 = new QLabel(centralWidget);
        labelSlot1_2->setObjectName(QStringLiteral("labelSlot1_2"));
        labelSlot1_2->setGeometry(QRect(100, 190, 81, 21));
        labelSlot1_3 = new QLabel(centralWidget);
        labelSlot1_3->setObjectName(QStringLiteral("labelSlot1_3"));
        labelSlot1_3->setGeometry(QRect(100, 220, 81, 21));
        labelSlot1_4 = new QLabel(centralWidget);
        labelSlot1_4->setObjectName(QStringLiteral("labelSlot1_4"));
        labelSlot1_4->setGeometry(QRect(100, 250, 81, 21));
        labelSlot1_5 = new QLabel(centralWidget);
        labelSlot1_5->setObjectName(QStringLiteral("labelSlot1_5"));
        labelSlot1_5->setGeometry(QRect(100, 280, 81, 21));
        labelSlot1_6 = new QLabel(centralWidget);
        labelSlot1_6->setObjectName(QStringLiteral("labelSlot1_6"));
        labelSlot1_6->setGeometry(QRect(100, 310, 81, 21));
        labelSlot1_7 = new QLabel(centralWidget);
        labelSlot1_7->setObjectName(QStringLiteral("labelSlot1_7"));
        labelSlot1_7->setGeometry(QRect(100, 340, 81, 21));
        labelSlot1_8 = new QLabel(centralWidget);
        labelSlot1_8->setObjectName(QStringLiteral("labelSlot1_8"));
        labelSlot1_8->setGeometry(QRect(100, 370, 81, 21));
        labelSlot1_9 = new QLabel(centralWidget);
        labelSlot1_9->setObjectName(QStringLiteral("labelSlot1_9"));
        labelSlot1_9->setGeometry(QRect(100, 400, 81, 21));
        labelSlot1_10 = new QLabel(centralWidget);
        labelSlot1_10->setObjectName(QStringLiteral("labelSlot1_10"));
        labelSlot1_10->setGeometry(QRect(100, 430, 81, 21));
        labelSlot1_11 = new QLabel(centralWidget);
        labelSlot1_11->setObjectName(QStringLiteral("labelSlot1_11"));
        labelSlot1_11->setGeometry(QRect(100, 460, 81, 21));
        labelSlot1_12 = new QLabel(centralWidget);
        labelSlot1_12->setObjectName(QStringLiteral("labelSlot1_12"));
        labelSlot1_12->setGeometry(QRect(100, 490, 81, 21));
        labelSlot1_13 = new QLabel(centralWidget);
        labelSlot1_13->setObjectName(QStringLiteral("labelSlot1_13"));
        labelSlot1_13->setGeometry(QRect(100, 520, 81, 21));
        labelSlot1_14 = new QLabel(centralWidget);
        labelSlot1_14->setObjectName(QStringLiteral("labelSlot1_14"));
        labelSlot1_14->setGeometry(QRect(100, 550, 81, 21));
        labelSlot1_15 = new QLabel(centralWidget);
        labelSlot1_15->setObjectName(QStringLiteral("labelSlot1_15"));
        labelSlot1_15->setGeometry(QRect(100, 580, 81, 21));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(1010, 120, 51, 21));
        lineEditName1_1 = new QLineEdit(centralWidget);
        lineEditName1_1->setObjectName(QStringLiteral("lineEditName1_1"));
        lineEditName1_1->setGeometry(QRect(170, 160, 71, 20));
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(190, 120, 31, 21));
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(280, 120, 31, 21));
        comboBoxSex1 = new QComboBox(centralWidget);
        comboBoxSex1->setObjectName(QStringLiteral("comboBoxSex1"));
        comboBoxSex1->setGeometry(QRect(260, 160, 69, 21));
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(490, 120, 21, 20));
        lineEditPH_1 = new QLineEdit(centralWidget);
        lineEditPH_1->setObjectName(QStringLiteral("lineEditPH_1"));
        lineEditPH_1->setGeometry(QRect(480, 160, 41, 20));
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(380, 120, 51, 21));
        label_1time = new QLabel(centralWidget);
        label_1time->setObjectName(QStringLiteral("label_1time"));
        label_1time->setGeometry(QRect(1020, 160, 54, 21));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 120, 54, 21));
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(250, 90, 111, 16));
        labeltempCondition = new QLabel(centralWidget);
        labeltempCondition->setObjectName(QStringLiteral("labeltempCondition"));
        labeltempCondition->setGeometry(QRect(360, 90, 54, 16));
        saveButton1 = new QPushButton(centralWidget);
        saveButton1->setObjectName(QStringLiteral("saveButton1"));
        saveButton1->setGeometry(QRect(1090, 160, 75, 23));
        saveButton2 = new QPushButton(centralWidget);
        saveButton2->setObjectName(QStringLiteral("saveButton2"));
        saveButton2->setGeometry(QRect(1090, 190, 75, 23));
        saveButton3 = new QPushButton(centralWidget);
        saveButton3->setObjectName(QStringLiteral("saveButton3"));
        saveButton3->setGeometry(QRect(1090, 220, 75, 23));
        saveButton4 = new QPushButton(centralWidget);
        saveButton4->setObjectName(QStringLiteral("saveButton4"));
        saveButton4->setGeometry(QRect(1090, 250, 75, 23));
        saveButton5 = new QPushButton(centralWidget);
        saveButton5->setObjectName(QStringLiteral("saveButton5"));
        saveButton5->setGeometry(QRect(1090, 280, 75, 23));
        saveButton6 = new QPushButton(centralWidget);
        saveButton6->setObjectName(QStringLiteral("saveButton6"));
        saveButton6->setGeometry(QRect(1090, 310, 75, 23));
        saveButton7 = new QPushButton(centralWidget);
        saveButton7->setObjectName(QStringLiteral("saveButton7"));
        saveButton7->setGeometry(QRect(1090, 340, 75, 23));
        saveButton8 = new QPushButton(centralWidget);
        saveButton8->setObjectName(QStringLiteral("saveButton8"));
        saveButton8->setGeometry(QRect(1090, 370, 75, 23));
        saveButton9 = new QPushButton(centralWidget);
        saveButton9->setObjectName(QStringLiteral("saveButton9"));
        saveButton9->setGeometry(QRect(1090, 400, 75, 23));
        saveButton10 = new QPushButton(centralWidget);
        saveButton10->setObjectName(QStringLiteral("saveButton10"));
        saveButton10->setGeometry(QRect(1090, 430, 75, 23));
        saveButton11 = new QPushButton(centralWidget);
        saveButton11->setObjectName(QStringLiteral("saveButton11"));
        saveButton11->setGeometry(QRect(1090, 460, 75, 23));
        saveButton12 = new QPushButton(centralWidget);
        saveButton12->setObjectName(QStringLiteral("saveButton12"));
        saveButton12->setGeometry(QRect(1090, 490, 75, 23));
        saveButton13 = new QPushButton(centralWidget);
        saveButton13->setObjectName(QStringLiteral("saveButton13"));
        saveButton13->setGeometry(QRect(1090, 520, 75, 23));
        saveButton14 = new QPushButton(centralWidget);
        saveButton14->setObjectName(QStringLiteral("saveButton14"));
        saveButton14->setGeometry(QRect(1090, 550, 75, 23));
        saveButton15 = new QPushButton(centralWidget);
        saveButton15->setObjectName(QStringLiteral("saveButton15"));
        saveButton15->setGeometry(QRect(1090, 580, 75, 23));
        lineEditName1_2 = new QLineEdit(centralWidget);
        lineEditName1_2->setObjectName(QStringLiteral("lineEditName1_2"));
        lineEditName1_2->setGeometry(QRect(170, 190, 71, 20));
        lineEditName1_3 = new QLineEdit(centralWidget);
        lineEditName1_3->setObjectName(QStringLiteral("lineEditName1_3"));
        lineEditName1_3->setGeometry(QRect(170, 220, 71, 20));
        lineEditName1_4 = new QLineEdit(centralWidget);
        lineEditName1_4->setObjectName(QStringLiteral("lineEditName1_4"));
        lineEditName1_4->setGeometry(QRect(170, 250, 71, 20));
        lineEditName1_5 = new QLineEdit(centralWidget);
        lineEditName1_5->setObjectName(QStringLiteral("lineEditName1_5"));
        lineEditName1_5->setGeometry(QRect(170, 280, 71, 20));
        lineEditName1_6 = new QLineEdit(centralWidget);
        lineEditName1_6->setObjectName(QStringLiteral("lineEditName1_6"));
        lineEditName1_6->setGeometry(QRect(170, 310, 71, 20));
        lineEditName1_7 = new QLineEdit(centralWidget);
        lineEditName1_7->setObjectName(QStringLiteral("lineEditName1_7"));
        lineEditName1_7->setGeometry(QRect(170, 340, 71, 20));
        lineEditName1_8 = new QLineEdit(centralWidget);
        lineEditName1_8->setObjectName(QStringLiteral("lineEditName1_8"));
        lineEditName1_8->setGeometry(QRect(170, 370, 71, 20));
        lineEditName1_9 = new QLineEdit(centralWidget);
        lineEditName1_9->setObjectName(QStringLiteral("lineEditName1_9"));
        lineEditName1_9->setGeometry(QRect(170, 400, 71, 20));
        lineEditName1_10 = new QLineEdit(centralWidget);
        lineEditName1_10->setObjectName(QStringLiteral("lineEditName1_10"));
        lineEditName1_10->setGeometry(QRect(170, 430, 71, 20));
        lineEditName1_11 = new QLineEdit(centralWidget);
        lineEditName1_11->setObjectName(QStringLiteral("lineEditName1_11"));
        lineEditName1_11->setGeometry(QRect(170, 460, 71, 20));
        lineEditName1_12 = new QLineEdit(centralWidget);
        lineEditName1_12->setObjectName(QStringLiteral("lineEditName1_12"));
        lineEditName1_12->setGeometry(QRect(170, 490, 71, 20));
        lineEditName1_13 = new QLineEdit(centralWidget);
        lineEditName1_13->setObjectName(QStringLiteral("lineEditName1_13"));
        lineEditName1_13->setGeometry(QRect(170, 520, 71, 20));
        lineEditName1_14 = new QLineEdit(centralWidget);
        lineEditName1_14->setObjectName(QStringLiteral("lineEditName1_14"));
        lineEditName1_14->setGeometry(QRect(170, 550, 71, 20));
        lineEditName1_15 = new QLineEdit(centralWidget);
        lineEditName1_15->setObjectName(QStringLiteral("lineEditName1_15"));
        lineEditName1_15->setGeometry(QRect(170, 580, 71, 20));
        comboBoxSex1_2 = new QComboBox(centralWidget);
        comboBoxSex1_2->setObjectName(QStringLiteral("comboBoxSex1_2"));
        comboBoxSex1_2->setGeometry(QRect(260, 190, 69, 21));
        comboBoxSex1_3 = new QComboBox(centralWidget);
        comboBoxSex1_3->setObjectName(QStringLiteral("comboBoxSex1_3"));
        comboBoxSex1_3->setGeometry(QRect(260, 220, 69, 21));
        comboBoxSex1_4 = new QComboBox(centralWidget);
        comboBoxSex1_4->setObjectName(QStringLiteral("comboBoxSex1_4"));
        comboBoxSex1_4->setGeometry(QRect(260, 250, 69, 21));
        comboBoxSex1_5 = new QComboBox(centralWidget);
        comboBoxSex1_5->setObjectName(QStringLiteral("comboBoxSex1_5"));
        comboBoxSex1_5->setGeometry(QRect(260, 280, 69, 21));
        comboBoxSex1_6 = new QComboBox(centralWidget);
        comboBoxSex1_6->setObjectName(QStringLiteral("comboBoxSex1_6"));
        comboBoxSex1_6->setGeometry(QRect(260, 310, 69, 21));
        comboBoxSex1_7 = new QComboBox(centralWidget);
        comboBoxSex1_7->setObjectName(QStringLiteral("comboBoxSex1_7"));
        comboBoxSex1_7->setGeometry(QRect(260, 340, 69, 21));
        comboBoxSex1_8 = new QComboBox(centralWidget);
        comboBoxSex1_8->setObjectName(QStringLiteral("comboBoxSex1_8"));
        comboBoxSex1_8->setGeometry(QRect(260, 370, 69, 21));
        comboBoxSex1_9 = new QComboBox(centralWidget);
        comboBoxSex1_9->setObjectName(QStringLiteral("comboBoxSex1_9"));
        comboBoxSex1_9->setGeometry(QRect(260, 400, 69, 21));
        comboBoxSex1_10 = new QComboBox(centralWidget);
        comboBoxSex1_10->setObjectName(QStringLiteral("comboBoxSex1_10"));
        comboBoxSex1_10->setGeometry(QRect(260, 430, 69, 21));
        comboBoxSex1_11 = new QComboBox(centralWidget);
        comboBoxSex1_11->setObjectName(QStringLiteral("comboBoxSex1_11"));
        comboBoxSex1_11->setGeometry(QRect(260, 460, 69, 21));
        comboBoxSex1_12 = new QComboBox(centralWidget);
        comboBoxSex1_12->setObjectName(QStringLiteral("comboBoxSex1_12"));
        comboBoxSex1_12->setGeometry(QRect(260, 490, 69, 21));
        comboBoxSex1_13 = new QComboBox(centralWidget);
        comboBoxSex1_13->setObjectName(QStringLiteral("comboBoxSex1_13"));
        comboBoxSex1_13->setGeometry(QRect(260, 520, 69, 21));
        comboBoxSex1_14 = new QComboBox(centralWidget);
        comboBoxSex1_14->setObjectName(QStringLiteral("comboBoxSex1_14"));
        comboBoxSex1_14->setGeometry(QRect(260, 550, 69, 21));
        comboBoxSex1_15 = new QComboBox(centralWidget);
        comboBoxSex1_15->setObjectName(QStringLiteral("comboBoxSex1_15"));
        comboBoxSex1_15->setGeometry(QRect(260, 580, 69, 21));
        lineEditPH_2 = new QLineEdit(centralWidget);
        lineEditPH_2->setObjectName(QStringLiteral("lineEditPH_2"));
        lineEditPH_2->setGeometry(QRect(480, 190, 41, 20));
        lineEditPH_3 = new QLineEdit(centralWidget);
        lineEditPH_3->setObjectName(QStringLiteral("lineEditPH_3"));
        lineEditPH_3->setGeometry(QRect(480, 220, 41, 20));
        lineEditPH_4 = new QLineEdit(centralWidget);
        lineEditPH_4->setObjectName(QStringLiteral("lineEditPH_4"));
        lineEditPH_4->setGeometry(QRect(480, 250, 41, 20));
        lineEditPH_5 = new QLineEdit(centralWidget);
        lineEditPH_5->setObjectName(QStringLiteral("lineEditPH_5"));
        lineEditPH_5->setGeometry(QRect(480, 280, 41, 20));
        lineEditPH_6 = new QLineEdit(centralWidget);
        lineEditPH_6->setObjectName(QStringLiteral("lineEditPH_6"));
        lineEditPH_6->setGeometry(QRect(480, 310, 41, 20));
        lineEditPH_7 = new QLineEdit(centralWidget);
        lineEditPH_7->setObjectName(QStringLiteral("lineEditPH_7"));
        lineEditPH_7->setGeometry(QRect(480, 340, 41, 20));
        lineEditPH_8 = new QLineEdit(centralWidget);
        lineEditPH_8->setObjectName(QStringLiteral("lineEditPH_8"));
        lineEditPH_8->setGeometry(QRect(480, 370, 41, 20));
        lineEditPH_9 = new QLineEdit(centralWidget);
        lineEditPH_9->setObjectName(QStringLiteral("lineEditPH_9"));
        lineEditPH_9->setGeometry(QRect(480, 400, 41, 20));
        lineEditPH_10 = new QLineEdit(centralWidget);
        lineEditPH_10->setObjectName(QStringLiteral("lineEditPH_10"));
        lineEditPH_10->setGeometry(QRect(480, 430, 41, 20));
        lineEditPH_11 = new QLineEdit(centralWidget);
        lineEditPH_11->setObjectName(QStringLiteral("lineEditPH_11"));
        lineEditPH_11->setGeometry(QRect(480, 460, 41, 20));
        lineEditPH_12 = new QLineEdit(centralWidget);
        lineEditPH_12->setObjectName(QStringLiteral("lineEditPH_12"));
        lineEditPH_12->setGeometry(QRect(480, 490, 41, 20));
        lineEditPH_13 = new QLineEdit(centralWidget);
        lineEditPH_13->setObjectName(QStringLiteral("lineEditPH_13"));
        lineEditPH_13->setGeometry(QRect(480, 520, 41, 20));
        lineEditPH_14 = new QLineEdit(centralWidget);
        lineEditPH_14->setObjectName(QStringLiteral("lineEditPH_14"));
        lineEditPH_14->setGeometry(QRect(480, 550, 41, 20));
        lineEditPH_15 = new QLineEdit(centralWidget);
        lineEditPH_15->setObjectName(QStringLiteral("lineEditPH_15"));
        lineEditPH_15->setGeometry(QRect(480, 580, 41, 20));
        label_1time_2 = new QLabel(centralWidget);
        label_1time_2->setObjectName(QStringLiteral("label_1time_2"));
        label_1time_2->setGeometry(QRect(1020, 190, 54, 21));
        label_1time_3 = new QLabel(centralWidget);
        label_1time_3->setObjectName(QStringLiteral("label_1time_3"));
        label_1time_3->setGeometry(QRect(1020, 220, 54, 21));
        label_1time_4 = new QLabel(centralWidget);
        label_1time_4->setObjectName(QStringLiteral("label_1time_4"));
        label_1time_4->setGeometry(QRect(1020, 250, 54, 21));
        label_1time_5 = new QLabel(centralWidget);
        label_1time_5->setObjectName(QStringLiteral("label_1time_5"));
        label_1time_5->setGeometry(QRect(1020, 280, 54, 21));
        label_1time_6 = new QLabel(centralWidget);
        label_1time_6->setObjectName(QStringLiteral("label_1time_6"));
        label_1time_6->setGeometry(QRect(1020, 310, 54, 21));
        label_1time_7 = new QLabel(centralWidget);
        label_1time_7->setObjectName(QStringLiteral("label_1time_7"));
        label_1time_7->setGeometry(QRect(1020, 340, 54, 21));
        label_1time_8 = new QLabel(centralWidget);
        label_1time_8->setObjectName(QStringLiteral("label_1time_8"));
        label_1time_8->setGeometry(QRect(1020, 370, 54, 21));
        label_1time_9 = new QLabel(centralWidget);
        label_1time_9->setObjectName(QStringLiteral("label_1time_9"));
        label_1time_9->setGeometry(QRect(1020, 400, 54, 21));
        label_1time_10 = new QLabel(centralWidget);
        label_1time_10->setObjectName(QStringLiteral("label_1time_10"));
        label_1time_10->setGeometry(QRect(1020, 430, 54, 21));
        label_1time_11 = new QLabel(centralWidget);
        label_1time_11->setObjectName(QStringLiteral("label_1time_11"));
        label_1time_11->setGeometry(QRect(1020, 460, 54, 21));
        label_1time_12 = new QLabel(centralWidget);
        label_1time_12->setObjectName(QStringLiteral("label_1time_12"));
        label_1time_12->setGeometry(QRect(1020, 490, 54, 21));
        label_1time_13 = new QLabel(centralWidget);
        label_1time_13->setObjectName(QStringLiteral("label_1time_13"));
        label_1time_13->setGeometry(QRect(1020, 520, 54, 21));
        label_1time_14 = new QLabel(centralWidget);
        label_1time_14->setObjectName(QStringLiteral("label_1time_14"));
        label_1time_14->setGeometry(QRect(1020, 550, 54, 21));
        label_1time_15 = new QLabel(centralWidget);
        label_1time_15->setObjectName(QStringLiteral("label_1time_15"));
        label_1time_15->setGeometry(QRect(1020, 580, 54, 21));
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(1100, 120, 54, 20));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(1090, 30, 75, 23));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(560, 120, 21, 21));
        lineEditNAG_1 = new QLineEdit(centralWidget);
        lineEditNAG_1->setObjectName(QStringLiteral("lineEditNAG_1"));
        lineEditNAG_1->setGeometry(QRect(540, 160, 71, 20));
        lineEditNAG_2 = new QLineEdit(centralWidget);
        lineEditNAG_2->setObjectName(QStringLiteral("lineEditNAG_2"));
        lineEditNAG_2->setGeometry(QRect(540, 190, 71, 20));
        lineEditNAG_3 = new QLineEdit(centralWidget);
        lineEditNAG_3->setObjectName(QStringLiteral("lineEditNAG_3"));
        lineEditNAG_3->setGeometry(QRect(540, 220, 71, 20));
        lineEditNAG_4 = new QLineEdit(centralWidget);
        lineEditNAG_4->setObjectName(QStringLiteral("lineEditNAG_4"));
        lineEditNAG_4->setGeometry(QRect(540, 250, 71, 20));
        lineEditNAG_5 = new QLineEdit(centralWidget);
        lineEditNAG_5->setObjectName(QStringLiteral("lineEditNAG_5"));
        lineEditNAG_5->setGeometry(QRect(540, 280, 71, 20));
        lineEditNAG_6 = new QLineEdit(centralWidget);
        lineEditNAG_6->setObjectName(QStringLiteral("lineEditNAG_6"));
        lineEditNAG_6->setGeometry(QRect(540, 310, 71, 20));
        lineEditNAG_7 = new QLineEdit(centralWidget);
        lineEditNAG_7->setObjectName(QStringLiteral("lineEditNAG_7"));
        lineEditNAG_7->setGeometry(QRect(540, 340, 71, 20));
        lineEditNAG_8 = new QLineEdit(centralWidget);
        lineEditNAG_8->setObjectName(QStringLiteral("lineEditNAG_8"));
        lineEditNAG_8->setGeometry(QRect(540, 370, 71, 20));
        lineEditNAG_9 = new QLineEdit(centralWidget);
        lineEditNAG_9->setObjectName(QStringLiteral("lineEditNAG_9"));
        lineEditNAG_9->setGeometry(QRect(540, 400, 71, 20));
        lineEditNAG_10 = new QLineEdit(centralWidget);
        lineEditNAG_10->setObjectName(QStringLiteral("lineEditNAG_10"));
        lineEditNAG_10->setGeometry(QRect(540, 430, 71, 20));
        lineEditNAG_11 = new QLineEdit(centralWidget);
        lineEditNAG_11->setObjectName(QStringLiteral("lineEditNAG_11"));
        lineEditNAG_11->setGeometry(QRect(540, 460, 71, 20));
        lineEditNAG_12 = new QLineEdit(centralWidget);
        lineEditNAG_12->setObjectName(QStringLiteral("lineEditNAG_12"));
        lineEditNAG_12->setGeometry(QRect(540, 490, 71, 20));
        lineEditNAG_13 = new QLineEdit(centralWidget);
        lineEditNAG_13->setObjectName(QStringLiteral("lineEditNAG_13"));
        lineEditNAG_13->setGeometry(QRect(540, 520, 71, 20));
        lineEditNAG_14 = new QLineEdit(centralWidget);
        lineEditNAG_14->setObjectName(QStringLiteral("lineEditNAG_14"));
        lineEditNAG_14->setGeometry(QRect(540, 550, 71, 20));
        lineEditNAG_15 = new QLineEdit(centralWidget);
        lineEditNAG_15->setObjectName(QStringLiteral("lineEditNAG_15"));
        lineEditNAG_15->setGeometry(QRect(540, 580, 71, 20));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(650, 120, 21, 21));
        lineEditPLD_1 = new QLineEdit(centralWidget);
        lineEditPLD_1->setObjectName(QStringLiteral("lineEditPLD_1"));
        lineEditPLD_1->setGeometry(QRect(620, 160, 81, 20));
        lineEditPLD_2 = new QLineEdit(centralWidget);
        lineEditPLD_2->setObjectName(QStringLiteral("lineEditPLD_2"));
        lineEditPLD_2->setGeometry(QRect(620, 190, 81, 20));
        lineEditPLD_3 = new QLineEdit(centralWidget);
        lineEditPLD_3->setObjectName(QStringLiteral("lineEditPLD_3"));
        lineEditPLD_3->setGeometry(QRect(620, 220, 81, 20));
        lineEditPLD_4 = new QLineEdit(centralWidget);
        lineEditPLD_4->setObjectName(QStringLiteral("lineEditPLD_4"));
        lineEditPLD_4->setGeometry(QRect(620, 250, 81, 20));
        lineEditPLD_5 = new QLineEdit(centralWidget);
        lineEditPLD_5->setObjectName(QStringLiteral("lineEditPLD_5"));
        lineEditPLD_5->setGeometry(QRect(620, 280, 81, 20));
        lineEditPLD_6 = new QLineEdit(centralWidget);
        lineEditPLD_6->setObjectName(QStringLiteral("lineEditPLD_6"));
        lineEditPLD_6->setGeometry(QRect(620, 310, 81, 20));
        lineEditPLD_7 = new QLineEdit(centralWidget);
        lineEditPLD_7->setObjectName(QStringLiteral("lineEditPLD_7"));
        lineEditPLD_7->setGeometry(QRect(620, 340, 81, 20));
        lineEditPLD_8 = new QLineEdit(centralWidget);
        lineEditPLD_8->setObjectName(QStringLiteral("lineEditPLD_8"));
        lineEditPLD_8->setGeometry(QRect(620, 370, 81, 20));
        lineEditPLD_9 = new QLineEdit(centralWidget);
        lineEditPLD_9->setObjectName(QStringLiteral("lineEditPLD_9"));
        lineEditPLD_9->setGeometry(QRect(620, 400, 81, 20));
        lineEditPLD_10 = new QLineEdit(centralWidget);
        lineEditPLD_10->setObjectName(QStringLiteral("lineEditPLD_10"));
        lineEditPLD_10->setGeometry(QRect(620, 430, 81, 20));
        lineEditPLD_11 = new QLineEdit(centralWidget);
        lineEditPLD_11->setObjectName(QStringLiteral("lineEditPLD_11"));
        lineEditPLD_11->setGeometry(QRect(620, 460, 81, 20));
        lineEditPLD_12 = new QLineEdit(centralWidget);
        lineEditPLD_12->setObjectName(QStringLiteral("lineEditPLD_12"));
        lineEditPLD_12->setGeometry(QRect(620, 490, 81, 20));
        lineEditPLD_13 = new QLineEdit(centralWidget);
        lineEditPLD_13->setObjectName(QStringLiteral("lineEditPLD_13"));
        lineEditPLD_13->setGeometry(QRect(620, 520, 81, 20));
        lineEditPLD_14 = new QLineEdit(centralWidget);
        lineEditPLD_14->setObjectName(QStringLiteral("lineEditPLD_14"));
        lineEditPLD_14->setGeometry(QRect(620, 550, 81, 20));
        lineEditPLD_15 = new QLineEdit(centralWidget);
        lineEditPLD_15->setObjectName(QStringLiteral("lineEditPLD_15"));
        lineEditPLD_15->setGeometry(QRect(620, 580, 81, 20));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(750, 120, 54, 20));
        lineEditSIA_1 = new QLineEdit(centralWidget);
        lineEditSIA_1->setObjectName(QStringLiteral("lineEditSIA_1"));
        lineEditSIA_1->setGeometry(QRect(720, 160, 91, 20));
        lineEditSIA_2 = new QLineEdit(centralWidget);
        lineEditSIA_2->setObjectName(QStringLiteral("lineEditSIA_2"));
        lineEditSIA_2->setGeometry(QRect(720, 190, 91, 20));
        lineEditSIA_3 = new QLineEdit(centralWidget);
        lineEditSIA_3->setObjectName(QStringLiteral("lineEditSIA_3"));
        lineEditSIA_3->setGeometry(QRect(720, 220, 91, 20));
        lineEditSIA_4 = new QLineEdit(centralWidget);
        lineEditSIA_4->setObjectName(QStringLiteral("lineEditSIA_4"));
        lineEditSIA_4->setGeometry(QRect(720, 250, 91, 20));
        lineEditSIA_5 = new QLineEdit(centralWidget);
        lineEditSIA_5->setObjectName(QStringLiteral("lineEditSIA_5"));
        lineEditSIA_5->setGeometry(QRect(720, 280, 91, 20));
        lineEditSIA_6 = new QLineEdit(centralWidget);
        lineEditSIA_6->setObjectName(QStringLiteral("lineEditSIA_6"));
        lineEditSIA_6->setGeometry(QRect(720, 310, 91, 20));
        lineEditSIA_7 = new QLineEdit(centralWidget);
        lineEditSIA_7->setObjectName(QStringLiteral("lineEditSIA_7"));
        lineEditSIA_7->setGeometry(QRect(720, 340, 91, 20));
        lineEditSIA_8 = new QLineEdit(centralWidget);
        lineEditSIA_8->setObjectName(QStringLiteral("lineEditSIA_8"));
        lineEditSIA_8->setGeometry(QRect(720, 370, 91, 20));
        lineEditSIA_9 = new QLineEdit(centralWidget);
        lineEditSIA_9->setObjectName(QStringLiteral("lineEditSIA_9"));
        lineEditSIA_9->setGeometry(QRect(720, 400, 91, 20));
        lineEditSIA_10 = new QLineEdit(centralWidget);
        lineEditSIA_10->setObjectName(QStringLiteral("lineEditSIA_10"));
        lineEditSIA_10->setGeometry(QRect(720, 430, 91, 20));
        lineEditSIA_11 = new QLineEdit(centralWidget);
        lineEditSIA_11->setObjectName(QStringLiteral("lineEditSIA_11"));
        lineEditSIA_11->setGeometry(QRect(720, 460, 91, 20));
        lineEditSIA_12 = new QLineEdit(centralWidget);
        lineEditSIA_12->setObjectName(QStringLiteral("lineEditSIA_12"));
        lineEditSIA_12->setGeometry(QRect(720, 490, 91, 20));
        lineEditSIA_13 = new QLineEdit(centralWidget);
        lineEditSIA_13->setObjectName(QStringLiteral("lineEditSIA_13"));
        lineEditSIA_13->setGeometry(QRect(720, 520, 91, 20));
        lineEditSIA_14 = new QLineEdit(centralWidget);
        lineEditSIA_14->setObjectName(QStringLiteral("lineEditSIA_14"));
        lineEditSIA_14->setGeometry(QRect(720, 550, 91, 20));
        lineEditSIA_15 = new QLineEdit(centralWidget);
        lineEditSIA_15->setObjectName(QStringLiteral("lineEditSIA_15"));
        lineEditSIA_15->setGeometry(QRect(720, 580, 91, 20));
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(850, 120, 54, 20));
        lineEditLE_1 = new QLineEdit(centralWidget);
        lineEditLE_1->setObjectName(QStringLiteral("lineEditLE_1"));
        lineEditLE_1->setGeometry(QRect(830, 160, 71, 20));
        lineEditLE_2 = new QLineEdit(centralWidget);
        lineEditLE_2->setObjectName(QStringLiteral("lineEditLE_2"));
        lineEditLE_2->setGeometry(QRect(830, 190, 71, 20));
        lineEditLE_3 = new QLineEdit(centralWidget);
        lineEditLE_3->setObjectName(QStringLiteral("lineEditLE_3"));
        lineEditLE_3->setGeometry(QRect(830, 220, 71, 20));
        lineEditLE_4 = new QLineEdit(centralWidget);
        lineEditLE_4->setObjectName(QStringLiteral("lineEditLE_4"));
        lineEditLE_4->setGeometry(QRect(830, 250, 71, 20));
        lineEditLE_5 = new QLineEdit(centralWidget);
        lineEditLE_5->setObjectName(QStringLiteral("lineEditLE_5"));
        lineEditLE_5->setGeometry(QRect(830, 280, 71, 20));
        lineEditLE_6 = new QLineEdit(centralWidget);
        lineEditLE_6->setObjectName(QStringLiteral("lineEditLE_6"));
        lineEditLE_6->setGeometry(QRect(830, 310, 71, 20));
        lineEditLE_7 = new QLineEdit(centralWidget);
        lineEditLE_7->setObjectName(QStringLiteral("lineEditLE_7"));
        lineEditLE_7->setGeometry(QRect(830, 340, 71, 20));
        lineEditLE_8 = new QLineEdit(centralWidget);
        lineEditLE_8->setObjectName(QStringLiteral("lineEditLE_8"));
        lineEditLE_8->setGeometry(QRect(830, 370, 71, 20));
        lineEditLE_9 = new QLineEdit(centralWidget);
        lineEditLE_9->setObjectName(QStringLiteral("lineEditLE_9"));
        lineEditLE_9->setGeometry(QRect(830, 400, 71, 20));
        lineEditLE_10 = new QLineEdit(centralWidget);
        lineEditLE_10->setObjectName(QStringLiteral("lineEditLE_10"));
        lineEditLE_10->setGeometry(QRect(830, 430, 71, 20));
        lineEditLE_11 = new QLineEdit(centralWidget);
        lineEditLE_11->setObjectName(QStringLiteral("lineEditLE_11"));
        lineEditLE_11->setGeometry(QRect(830, 460, 71, 20));
        lineEditLE_12 = new QLineEdit(centralWidget);
        lineEditLE_12->setObjectName(QStringLiteral("lineEditLE_12"));
        lineEditLE_12->setGeometry(QRect(830, 490, 71, 20));
        lineEditLE_13 = new QLineEdit(centralWidget);
        lineEditLE_13->setObjectName(QStringLiteral("lineEditLE_13"));
        lineEditLE_13->setGeometry(QRect(830, 520, 71, 20));
        lineEditLE_14 = new QLineEdit(centralWidget);
        lineEditLE_14->setObjectName(QStringLiteral("lineEditLE_14"));
        lineEditLE_14->setGeometry(QRect(830, 550, 71, 20));
        lineEditLE_15 = new QLineEdit(centralWidget);
        lineEditLE_15->setObjectName(QStringLiteral("lineEditLE_15"));
        lineEditLE_15->setGeometry(QRect(830, 580, 71, 20));
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(930, 120, 31, 21));
        lineEditHH_1 = new QLineEdit(centralWidget);
        lineEditHH_1->setObjectName(QStringLiteral("lineEditHH_1"));
        lineEditHH_1->setGeometry(QRect(910, 160, 81, 20));
        lineEditHH_2 = new QLineEdit(centralWidget);
        lineEditHH_2->setObjectName(QStringLiteral("lineEditHH_2"));
        lineEditHH_2->setGeometry(QRect(910, 190, 81, 20));
        lineEditHH_3 = new QLineEdit(centralWidget);
        lineEditHH_3->setObjectName(QStringLiteral("lineEditHH_3"));
        lineEditHH_3->setGeometry(QRect(910, 220, 81, 20));
        lineEditHH_4 = new QLineEdit(centralWidget);
        lineEditHH_4->setObjectName(QStringLiteral("lineEditHH_4"));
        lineEditHH_4->setGeometry(QRect(910, 250, 81, 20));
        lineEditHH_5 = new QLineEdit(centralWidget);
        lineEditHH_5->setObjectName(QStringLiteral("lineEditHH_5"));
        lineEditHH_5->setGeometry(QRect(910, 280, 81, 20));
        lineEditHH_6 = new QLineEdit(centralWidget);
        lineEditHH_6->setObjectName(QStringLiteral("lineEditHH_6"));
        lineEditHH_6->setGeometry(QRect(910, 310, 81, 20));
        lineEditHH_7 = new QLineEdit(centralWidget);
        lineEditHH_7->setObjectName(QStringLiteral("lineEditHH_7"));
        lineEditHH_7->setGeometry(QRect(910, 340, 81, 20));
        lineEditHH_8 = new QLineEdit(centralWidget);
        lineEditHH_8->setObjectName(QStringLiteral("lineEditHH_8"));
        lineEditHH_8->setGeometry(QRect(910, 370, 81, 20));
        lineEditHH_9 = new QLineEdit(centralWidget);
        lineEditHH_9->setObjectName(QStringLiteral("lineEditHH_9"));
        lineEditHH_9->setGeometry(QRect(910, 400, 81, 20));
        lineEditHH_10 = new QLineEdit(centralWidget);
        lineEditHH_10->setObjectName(QStringLiteral("lineEditHH_10"));
        lineEditHH_10->setGeometry(QRect(910, 430, 81, 20));
        lineEditHH_11 = new QLineEdit(centralWidget);
        lineEditHH_11->setObjectName(QStringLiteral("lineEditHH_11"));
        lineEditHH_11->setGeometry(QRect(910, 460, 81, 20));
        lineEditHH_12 = new QLineEdit(centralWidget);
        lineEditHH_12->setObjectName(QStringLiteral("lineEditHH_12"));
        lineEditHH_12->setGeometry(QRect(910, 490, 81, 20));
        lineEditHH_13 = new QLineEdit(centralWidget);
        lineEditHH_13->setObjectName(QStringLiteral("lineEditHH_13"));
        lineEditHH_13->setGeometry(QRect(910, 520, 81, 20));
        lineEditHH_14 = new QLineEdit(centralWidget);
        lineEditHH_14->setObjectName(QStringLiteral("lineEditHH_14"));
        lineEditHH_14->setGeometry(QRect(910, 550, 81, 20));
        lineEditHH_15 = new QLineEdit(centralWidget);
        lineEditHH_15->setObjectName(QStringLiteral("lineEditHH_15"));
        lineEditHH_15->setGeometry(QRect(910, 580, 81, 20));
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(440, 90, 81, 16));
        filepath = new QLabel(centralWidget);
        filepath->setObjectName(QStringLiteral("filepath"));
        filepath->setGeometry(QRect(520, 90, 291, 16));
        lineEditNumber_1 = new QLineEdit(centralWidget);
        lineEditNumber_1->setObjectName(QStringLiteral("lineEditNumber_1"));
        lineEditNumber_1->setGeometry(QRect(350, 160, 113, 20));
        lineEditNumber_2 = new QLineEdit(centralWidget);
        lineEditNumber_2->setObjectName(QStringLiteral("lineEditNumber_2"));
        lineEditNumber_2->setGeometry(QRect(350, 190, 113, 20));
        lineEditNumber_3 = new QLineEdit(centralWidget);
        lineEditNumber_3->setObjectName(QStringLiteral("lineEditNumber_3"));
        lineEditNumber_3->setGeometry(QRect(350, 220, 113, 20));
        lineEditNumber_4 = new QLineEdit(centralWidget);
        lineEditNumber_4->setObjectName(QStringLiteral("lineEditNumber_4"));
        lineEditNumber_4->setGeometry(QRect(350, 250, 113, 20));
        lineEditNumber_5 = new QLineEdit(centralWidget);
        lineEditNumber_5->setObjectName(QStringLiteral("lineEditNumber_5"));
        lineEditNumber_5->setGeometry(QRect(350, 280, 113, 20));
        lineEditNumber_6 = new QLineEdit(centralWidget);
        lineEditNumber_6->setObjectName(QStringLiteral("lineEditNumber_6"));
        lineEditNumber_6->setGeometry(QRect(350, 310, 113, 20));
        lineEditNumber_7 = new QLineEdit(centralWidget);
        lineEditNumber_7->setObjectName(QStringLiteral("lineEditNumber_7"));
        lineEditNumber_7->setGeometry(QRect(350, 340, 113, 20));
        lineEditNumber_8 = new QLineEdit(centralWidget);
        lineEditNumber_8->setObjectName(QStringLiteral("lineEditNumber_8"));
        lineEditNumber_8->setGeometry(QRect(350, 370, 113, 20));
        lineEditNumber_9 = new QLineEdit(centralWidget);
        lineEditNumber_9->setObjectName(QStringLiteral("lineEditNumber_9"));
        lineEditNumber_9->setGeometry(QRect(350, 400, 113, 20));
        lineEditNumber_10 = new QLineEdit(centralWidget);
        lineEditNumber_10->setObjectName(QStringLiteral("lineEditNumber_10"));
        lineEditNumber_10->setGeometry(QRect(350, 430, 113, 20));
        lineEditNumber_11 = new QLineEdit(centralWidget);
        lineEditNumber_11->setObjectName(QStringLiteral("lineEditNumber_11"));
        lineEditNumber_11->setGeometry(QRect(350, 460, 113, 20));
        lineEditNumber_12 = new QLineEdit(centralWidget);
        lineEditNumber_12->setObjectName(QStringLiteral("lineEditNumber_12"));
        lineEditNumber_12->setGeometry(QRect(350, 490, 113, 20));
        lineEditNumber_13 = new QLineEdit(centralWidget);
        lineEditNumber_13->setObjectName(QStringLiteral("lineEditNumber_13"));
        lineEditNumber_13->setGeometry(QRect(350, 520, 113, 20));
        lineEditNumber_14 = new QLineEdit(centralWidget);
        lineEditNumber_14->setObjectName(QStringLiteral("lineEditNumber_14"));
        lineEditNumber_14->setGeometry(QRect(350, 550, 113, 20));
        lineEditNumber_15 = new QLineEdit(centralWidget);
        lineEditNumber_15->setObjectName(QStringLiteral("lineEditNumber_15"));
        lineEditNumber_15->setGeometry(QRect(350, 580, 113, 20));
        lcdNumber = new QLCDNumber(centralWidget);
        lcdNumber->setObjectName(QStringLiteral("lcdNumber"));
        lcdNumber->setGeometry(QRect(0, 50, 201, 21));
        QPalette palette;
        QBrush brush(QColor(8, 8, 8, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush);
        lcdNumber->setPalette(palette);
        lcdNumber->setLocale(QLocale(QLocale::English, QLocale::UnitedKingdom));
        lcdNumber->setDigitCount(20);
        lcdNumber_temperature = new QLCDNumber(centralWidget);
        lcdNumber_temperature->setObjectName(QStringLiteral("lcdNumber_temperature"));
        lcdNumber_temperature->setGeometry(QRect(110, 90, 121, 23));
        QPalette palette1;
        QBrush brush1(QColor(11, 11, 11, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        lcdNumber_temperature->setPalette(palette1);
        lcdNumber_temperature->setDigitCount(10);
        BVClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(BVClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1178, 23));
        menu = new QMenu(menuBar);
        menu->setObjectName(QStringLiteral("menu"));
        BVClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(BVClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        BVClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(BVClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        BVClass->setStatusBar(statusBar);

        menuBar->addAction(menu->menuAction());
        menu->addAction(action);
        menu->addAction(action2);

        retranslateUi(BVClass);
        QObject::connect(pushButton, SIGNAL(clicked()), BVClass, SLOT(close()));

        QMetaObject::connectSlotsByName(BVClass);
    } // setupUi

    void retranslateUi(QMainWindow *BVClass)
    {
        BVClass->setWindowTitle(QApplication::translate("BVClass", "\347\224\250\346\210\267\347\253\257V0.2", Q_NULLPTR));
        action->setText(QApplication::translate("BVClass", "\345\274\200\346\234\272\350\207\252\346\243\200", Q_NULLPTR));
        action2->setText(QApplication::translate("BVClass", "\346\225\260\346\215\256\345\202\250\345\255\230\350\267\257\345\276\204", Q_NULLPTR));
        label_2->setText(QApplication::translate("BVClass", "\346\270\251\350\202\262\347\273\264\346\214\201\346\270\251\345\272\246(\342\204\203)\357\274\232", Q_NULLPTR));
        pushButtonTemperature->setText(QApplication::translate("BVClass", "\345\274\200\345\247\213\345\212\240\347\203\255", Q_NULLPTR));
        pushButton->setText(QApplication::translate("BVClass", "EXIT", Q_NULLPTR));
        pushButtonSlot1->setText(QApplication::translate("BVClass", "01\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot2->setText(QApplication::translate("BVClass", "02\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot3->setText(QApplication::translate("BVClass", "03\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot4->setText(QApplication::translate("BVClass", "04\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot5->setText(QApplication::translate("BVClass", "05\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot6->setText(QApplication::translate("BVClass", "06\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot7->setText(QApplication::translate("BVClass", "07\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot8->setText(QApplication::translate("BVClass", "08\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot9->setText(QApplication::translate("BVClass", "09\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot10->setText(QApplication::translate("BVClass", "10\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot11->setText(QApplication::translate("BVClass", "11\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot12->setText(QApplication::translate("BVClass", "12\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot13->setText(QApplication::translate("BVClass", "13\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot14->setText(QApplication::translate("BVClass", "14\345\274\200\345\247\213", Q_NULLPTR));
        pushButtonSlot15->setText(QApplication::translate("BVClass", "15\345\274\200\345\247\213", Q_NULLPTR));
        label_4->setText(QApplication::translate("BVClass", "\345\267\245\344\275\234\346\247\275\347\212\266\346\200\201", Q_NULLPTR));
        labelSlot1_1->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_2->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_3->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_4->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_5->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_6->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_7->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_8->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_9->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_10->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_11->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_12->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_13->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_14->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        labelSlot1_15->setText(QApplication::translate("BVClass", "\347\251\272\351\227\262", Q_NULLPTR));
        label_5->setText(QApplication::translate("BVClass", "\346\211\200\347\224\250\346\227\266\351\227\264", Q_NULLPTR));
        label_6->setText(QApplication::translate("BVClass", "\345\247\223\345\220\215", Q_NULLPTR));
        label_7->setText(QApplication::translate("BVClass", "\346\200\247\345\210\253", Q_NULLPTR));
        comboBoxSex1->clear();
        comboBoxSex1->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        label_8->setText(QApplication::translate("BVClass", "PH", Q_NULLPTR));
        label_9->setText(QApplication::translate("BVClass", "\346\240\267\346\234\254\347\274\226\345\217\267", Q_NULLPTR));
        label_1time->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_11->setText(QApplication::translate("BVClass", "\345\267\245\344\275\234\346\247\275", Q_NULLPTR));
        label_12->setText(QApplication::translate("BVClass", "\346\270\251\350\202\262\345\212\240\347\203\255\345\267\245\344\275\234\347\212\266\346\200\201\357\274\232", Q_NULLPTR));
        labeltempCondition->setText(QApplication::translate("BVClass", "Normal", Q_NULLPTR));
        saveButton1->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton2->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton3->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton4->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton5->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton6->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton7->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton8->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton9->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton10->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton11->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton12->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton13->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton14->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        saveButton15->setText(QApplication::translate("BVClass", "SAVE", Q_NULLPTR));
        comboBoxSex1_2->clear();
        comboBoxSex1_2->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_3->clear();
        comboBoxSex1_3->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_4->clear();
        comboBoxSex1_4->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_5->clear();
        comboBoxSex1_5->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_6->clear();
        comboBoxSex1_6->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_7->clear();
        comboBoxSex1_7->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_8->clear();
        comboBoxSex1_8->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_9->clear();
        comboBoxSex1_9->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_10->clear();
        comboBoxSex1_10->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_11->clear();
        comboBoxSex1_11->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_12->clear();
        comboBoxSex1_12->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_13->clear();
        comboBoxSex1_13->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_14->clear();
        comboBoxSex1_14->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        comboBoxSex1_15->clear();
        comboBoxSex1_15->insertItems(0, QStringList()
         << QApplication::translate("BVClass", "\345\245\263", Q_NULLPTR)
         << QApplication::translate("BVClass", "\345\205\266\344\273\226", Q_NULLPTR)
        );
        label_1time_2->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_3->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_4->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_5->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_6->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_7->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_8->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_9->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_10->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_11->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_12->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_13->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_14->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_1time_15->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        label_10->setText(QApplication::translate("BVClass", "\345\202\250\345\255\230\346\225\260\346\215\256", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("BVClass", "\350\241\250\346\240\274\346\211\223\345\215\260", Q_NULLPTR));
        label->setText(QApplication::translate("BVClass", "NAG", Q_NULLPTR));
        label_13->setText(QApplication::translate("BVClass", "PLD", Q_NULLPTR));
        label_14->setText(QApplication::translate("BVClass", "SIA", Q_NULLPTR));
        label_15->setText(QApplication::translate("BVClass", "LE", Q_NULLPTR));
        label_16->setText(QApplication::translate("BVClass", "H2O2", Q_NULLPTR));
        label_17->setText(QApplication::translate("BVClass", "\346\225\260\346\215\256\344\277\235\345\255\230\350\267\257\345\276\204\357\274\232", Q_NULLPTR));
        filepath->setText(QApplication::translate("BVClass", "NULL", Q_NULLPTR));
        menu->setTitle(QApplication::translate("BVClass", "\350\217\234\345\215\225", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class BVClass: public Ui_BVClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_BV_H
