# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = BV
DESTDIR = ../x64/Debug
QT += core sql widgets gui
CONFIG += debug
DEFINES += WIN64 QT_DLL QT_SQL_LIB QT_WIDGETS_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Debug
INCLUDEPATH += D:/work/opencvBuild/msvc_2013_64/include
INCLUDEPATH += D:/work/opencvBuild/msvc_2013_64/include/opencv
INCLUDEPATH += D:/work/opencvBuild/msvc_2013_64/include/opencv2
LIBS += -lopencv_calib3d330d \
    -lopencv_core330d \
    -lopencv_dnn330d \
    -lopencv_features2d330d \
    -lopencv_flann330d \
    -lopencv_highgui330d \
    -lopencv_imgcodecs330d \
    -lopencv_imgproc330d \
    -lopencv_ml330d \
    -lopencv_objdetect330d \
    -lopencv_photo330d \
    -lopencv_shape330d \
    -lopencv_stitching330d \
    -lopencv_superres330d \
    -lopencv_video330d \
    -lopencv_videoio330d \
    -lopencv_videostab330d \
    -lopencv_calib3d330 \
    -lopencv_core330 \
    -lopencv_dnn330 \
    -lopencv_features2d330 \
    -lopencv_flann330 \
    -lopencv_highgui330 \
    -lopencv_imgcodecs330 \
    -lopencv_imgproc330 \
    -lopencv_ml330 \
    -lopencv_objdetect330 \
    -lopencv_photo330 \
    -lopencv_shape330 \
    -lopencv_stitching330 \
    -lopencv_superres330 \
    -lopencv_video330 \
    -lopencv_videoio330 \
    -lopencv_videostab330
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_calib3d330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_calib3d330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_core330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_core330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_dnn330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_dnn330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_flann330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_flann330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_highgui330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_highgui330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_imgcodecs330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_imgcodecs330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_imgproc330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_imgproc330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_ml330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_ml330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_objdetect330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_objdetect330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_photo330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_photo330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_shape330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_shape330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_stitching330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_stitching330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_superres330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_superres330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_video330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_video330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_videoio330.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_videoio330d.lib
LIBS += D:/work/opencvBuild/msvc_2013_64/x64/vc12/lib/opencv_stab330.lib
LIBS += D://work//opencvBuild//msvc_2013_64//x64//vc12//lib//opencv_stab330d.lib

DEPENDPATH += .
DEPENDPATH += D:/work/opencvBuild/msvc_2013_64/x64/vc12

MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(BV.pri)

FORMS += \
    mydialog.ui

HEADERS += \
    mydialog.h

SOURCES += \
    mydialog.cpp
